POST http://localhost:5000/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "testThree@email.com",
    "passwordhash":"password"
}

###
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "test@email.com",
    "passwordhash":"password"
}

###
POST http://localhost:5000/log/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NzM0OTE3LCJleHAiOjE2Mjk4MjEzMTd9.KoZsCjfNKadauFd9uVexYHKWwBCFY--aN3BsH1svSJQ

{
    "description": "A second log description for User known as test@email.com",
    "definition":"filling out the definition",
    "result": "great result"
}

###
GET http://localhost:5000/log/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5000/log/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NzM0OTE3LCJleHAiOjE2Mjk4MjEzMTd9.KoZsCjfNKadauFd9uVexYHKWwBCFY--aN3BsH1svSJQ

###
PUT http://localhost:5000/log/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NzM0OTE3LCJleHAiOjE2Mjk4MjEzMTd9.KoZsCjfNKadauFd9uVexYHKWwBCFY--aN3BsH1svSJQ

{
    "description": "This is really a nice description",
    "definition":"filling out the definition",
    "result": "successful result"
}

###
DELETE http://localhost:5000/log/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NjU3MjExLCJleHAiOjE2Mjk3NDM2MTF9.jVr2fQk7tJFJ1YVOXH1CBs3xFRiynsTXqNB5HQzQl44
